# Get editor completion based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Insert a blank line between shell commands
add_newline = false

[python]
symbol = "Py "
style = "bold yellow"
detect_extensions = ["py"]
detect_files = [
  ".python-version",
  "Pipfile",
  "__init__.py",
  "pyproject.toml",
  "requirements.txt",
]

[jobs]
symbol = "Jobs:"
style = "bold blue"

[cmd_duration]
min_time = 2000
format = "took [$duration](bold yellow)"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"
